import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import subsetFont from "subset-font";
import ts from "typescript";

const root = fileURLToPath(new URL("../", import.meta.url));
const output = path.join(root, "app/fonts/generated");

async function filesIn(directory, extension) {
  const entries = await readdir(directory, { withFileTypes: true });
  const lists = await Promise.all(entries.map((entry) => {
    const file = path.join(directory, entry.name);
    return entry.isDirectory() ? filesIn(file, extension) : file.endsWith(extension) ? [file] : [];
  }));
  return lists.flat().sort();
}

// Read strings and JSX text, excluding source comments and implementation names.
function sourceText(file, source) {
  const parsed = ts.createSourceFile(file, source, ts.ScriptTarget.Latest, true);
  const strings = [];
  function visit(node) {
    if (ts.isStringLiteralLike(node) || ts.isJsxText(node)
      || ts.isTemplateHead(node) || ts.isTemplateMiddle(node) || ts.isTemplateTail(node)) {
      strings.push(node.text);
    }
    ts.forEachChild(node, visit);
  }
  visit(parsed);
  return strings.join("");
}

// 译文（xxx.en.md / .ru.md / .ja.md）用各自语言的字体，不放进朱雀仿宋
const markdownFiles = (await filesIn(path.join(root, "content"), ".md")).filter((file) => !/\.(en|ru|ja)\.md$/.test(file));
const sourceFiles = [
  ...await filesIn(path.join(root, "app"), ".tsx"),
  ...await filesIn(path.join(root, "components"), ".tsx"),
  // lib 下的文案：站点信息、界面翻译（lib/i18n）等
  ...await filesIn(path.join(root, "lib"), ".ts"),
];
const text = (await Promise.all([
  ...markdownFiles.map((file) => readFile(file, "utf8")),
  ...sourceFiles.map(async (file) => sourceText(file, await readFile(file, "utf8"))),
])).join("");
// Latin text uses the existing western fonts. Sort for reproducible output.
// 俄文（西里尔字母）走 EB Garamond，日文假名走 Zen Old Mincho，不放进朱雀仿宋
const otherFonts = (code) => (code >= 0x0400 && code <= 0x04ff) || (code >= 0x3040 && code <= 0x30ff);
const characters = [...new Set([...text].filter((char) => {
  const code = char.codePointAt(0);
  return code > 0x7f && !otherFonts(code);
}))]
  .sort((a, b) => a.codePointAt(0) - b.codePointAt(0));
if (!characters.length) throw new Error("No non-ASCII text found for the Chinese font subset");

const source = await readFile(path.join(root, "scripts/fonts/zhuque-fangsong-v0.108.woff2"));
const font = await subsetFont(source, characters.join(""), {
  targetFormat: "woff2",
  preserveNameIds: [0, 7, 8, 9, 11, 12, 13, 14],
});
await mkdir(output, { recursive: true });
await writeFile(path.join(output, "zhuque.woff2"), font);
await writeFile(path.join(output, "zhuque.css"), `/* Generated by pnpm fonts; do not edit. */
@font-face {
  font-family: "Zhuque Fangsong (technical preview)";
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url("./zhuque.woff2") format("woff2");
  unicode-range: ${characters.map((char) => `U+${char.codePointAt(0).toString(16).toUpperCase()}`).join(",")};
}
`);
console.log(`Chinese font: ${characters.length} characters, ${(font.length / 1024).toFixed(1)} KiB, one WOFF2`);
